export type MenuItem = {
  name: string;
  price: number;
  description?: string;
};

export type MenuCategory = {
  category: string;
  items: MenuItem[];
};

export const menuData: MenuCategory[] = [
  {
    category: "Breakfast",
    items: [
      { name: "Pancake", price: 290 },
      { name: "French Toast", price: 225 },
      { name: "Aalu Paratha", price: 225 },
      { name: "Plain Paratha", price: 190 },
      { name: "Puri", price: 180 },
      { name: "Boiled Egg", price: 140 },
      { name: "Fried Egg", price: 160 },
      { name: "Sunny Side Up", price: 160 },
      { name: "Plain Omelette", price: 140 },
      { name: "Masala Omelette", price: 160 },
      { name: "Cheese Omelette", price: 250 },
    ],
  },
  {
    category: "Soups",
    items: [
      { name: "Veg Clear Soup", price: 150 },
      { name: "Chicken Clear Soup", price: 200 },
      { name: "Mix Clear Soup", price: 250 },
      { name: "Cream of Mushroom", price: 225 },
      { name: "Cream of Chicken", price: 250 },
    ],
  },
  {
    category: "Salads",
    items: [
      { name: "Green Salad", price: 195 },
      { name: "Chicken Caesar Salad", price: 300 },
      { name: "Fruit Salad", price: 350 },
      { name: "Fruit Platter", price: 575 },
    ],
  },
  {
    category: "Momo",
    items: [
      { name: "Veg Steam Momo", price: 165 },
      { name: "Veg Jhol Momo", price: 175 },
      { name: "Veg Fried Momo", price: 185 },
      { name: "Veg Kothey Momo", price: 195 },
      { name: "Veg Chilli Momo", price: 220 },
      { name: "Veg Sadheko Momo", price: 230 },
      { name: "Veg Sizzler Momo", price: 250 },
      { name: "Paneer Steam Momo", price: 245 },
      { name: "Paneer Jhol Momo", price: 265 },
      { name: "Paneer Fried Momo", price: 275 },
      { name: "Paneer Kothey Momo", price: 285 },
      { name: "Paneer Chilli Momo", price: 290 },
      { name: "Paneer Sadheko Momo", price: 300 },
      { name: "Paneer Sizzler Momo", price: 350 },
      { name: "Buff Steam Momo", price: 175 },
      { name: "Buff Jhol Momo", price: 195 },
      { name: "Buff Fried Momo", price: 205 },
      { name: "Buff Kothey Momo", price: 215 },
      { name: "Buff Chilli Momo", price: 240 },
      { name: "Buff Sadheko Momo", price: 260 },
      { name: "Buff Sizzler Momo", price: 300 },
      { name: "Chicken Steam Momo", price: 195 },
      { name: "Chicken Jhol Momo", price: 215 },
      { name: "Chicken Fried Momo", price: 225 },
      { name: "Chicken Kothey Momo", price: 235 },
      { name: "Chicken Chilli Momo", price: 260 },
      { name: "Chicken Sadheko Momo", price: 280 },
      { name: "Chicken Sizzler Momo", price: 325 },
    ],
  },
  {
    category: "Chowmein",
    items: [
      { name: "Veg Chowmin", price: 185 },
      { name: "Egg Chowmin", price: 205 },
      { name: "Chicken Chowmin", price: 255 },
      { name: "Buff Chowmin", price: 235 },
      { name: "Pork Chowmin", price: 265 },
      { name: "Mix Chowmin", price: 350 },
    ],
  },
  {
    category: "Fry Rice & Biryani",
    items: [
      { name: "Veg Fry Rice", price: 185 },
      { name: "Egg Fry Rice", price: 205 },
      { name: "Chicken Fry Rice", price: 255 },
      { name: "Buff Fry Rice", price: 235 },
      { name: "Pork Fry Rice", price: 265 },
      { name: "Mix Fry Rice", price: 300 },
      { name: "Veg Handi Biryani", price: 340 },
      { name: "Chicken Handi Biryani", price: 445 },
      { name: "Buff Handi Biryani", price: 430 },
      { name: "Fish Handi Biryani", price: 445 },
      { name: "Pork Handi Biryani", price: 445 },
      { name: "Mutton Handi Biryani", price: 695 },
      { name: "Veg Biryani", price: 290 },
      { name: "Chicken Biryani", price: 395 },
      { name: "Buff Biryani", price: 380 },
      { name: "Fish Biryani", price: 395 },
      { name: "Pork Biryani", price: 395 },
      { name: "Mutton Biryani", price: 650 },
      { name: "Chicken Katiya", price: 550 },
      { name: "Pork Katiya", price: 600 },
      { name: "Mutton Katiya", price: 750 },
    ],
  },
  {
    category: "Keema Noodles",
    items: [
      { name: "Veg Keema Noodles", price: 180 },
      { name: "Buff Keema Noodles", price: 225 },
      { name: "Chicken Keema Noodles", price: 250 },
      { name: "Pork Keema Noodles", price: 275 },
    ],
  },
  {
    category: "Khaja Set",
    items: [
      { name: "Veg Khaja Set", price: 260 },
      { name: "Buff Khaja Set", price: 335 },
      { name: "Chicken Khaja Set", price: 370 },
      { name: "Pork Khaja Set", price: 390 },
      { name: "Bhutan Khaja Set", price: 450 },
    ],
  },
  {
    category: "Sandwiches & Burgers",
    items: [
      { name: "Veg Sandwich", price: 250 },
      { name: "Egg Sandwich", price: 280 },
      { name: "Chicken Cheese Sandwich", price: 350 },
      { name: "Chicken Club Sandwich", price: 400 },
      { name: "Crunchy Fried Chicken Burger", price: 450 },
      { name: "Veg Burger", price: 310 },
      { name: "Chicken Burger", price: 390 },
    ],
  },
  {
    category: "Katti Roll",
    items: [
        { name: "Veg Katti Roll", price: 250 },
        { name: "Paneer Katti Roll", price: 350 },
        { name: "Egg Katti Roll", price: 290 },
        { name: "Chicken Katti Roll", price: 365 },
        { name: "Buff Katti Roll", price: 335 },
        { name: "Pork Katti Roll", price: 375 },
        { name: "Mix Katti Roll", price: 390 },
    ],
  },
  {
    category: "Spring Roll",
    items: [
        { name: "Veg Spring Roll", price: 225 },
        { name: "Paneer Spring Roll", price: 325 },
        { name: "Egg Spring Roll", price: 265 },
        { name: "Chicken Spring Roll", price: 340 },
        { name: "Buff Spring Roll", price: 310 },
        { name: "Pork Spring Roll", price: 350 },
        { name: "Mix Spring Roll", price: 375 },
    ],
  },
  {
    category: "Thukpa & Noodles",
    items: [
        { name: "Veg Thukpa", price: 185 },
        { name: "Egg Thukpa", price: 205 },
        { name: "Buff Thukpa", price: 235 },
        { name: "Chicken Thukpa", price: 255 },
        { name: "Pork Thukpa", price: 265 },
        { name: "Mix Thukpa", price: 350 },
        { name: "Veg Current Noodles", price: 140 },
        { name: "Egg Current Noodles", price: 170 },
        { name: "Buff Current Noodles", price: 180 },
        { name: "Chicken Current Noodles", price: 190 },
        { name: "Pork Current Noodles", price: 200 },
        { name: "Mix Current Noodles", price: 230 },
    ],
  },
  {
    category: "Corn Dog",
    items: [
      { name: "Full Cheese Corn Dog (2pcs)", price: 350 },
      { name: "Chicken & Cheese Corn Dog (2pcs)", price: 300 },
      { name: "Buff & Cheese Corn Dog (2pcs)", price: 300 },
    ],
  },
  {
    category: "Sizzler",
    items: [
      { name: "Paneer Sizzler", price: 495 },
      { name: "Chicken Sizzler", price: 475 },
      { name: "Pork Sizzler", price: 490 },
    ],
  },
  {
    category: "Pizza",
    items: [
      { name: "Margherita Pizza", price: 395 },
      { name: "Pizza De Sausage", price: 575 },
      { name: "Pizza Funghi", price: 450 },
      { name: "Mixed Pizza", price: 650 },
      { name: "Chicken Pizza", price: 525 },
      { name: "Pepperoni (Salami) Pizza", price: 625 },
    ],
  },
  {
    category: "Specials",
    items: [
      { name: "Pheasant (कालीज) Meat/1 whole", price: 3500 },
      { name: "Duck (हांस) Meat/1 whole", price: 2500 },
      { name: "Local Chicken Meat/1 whole", price: 2500 },
      { name: "Guinea Fowl (Laukat) Meat/1 whole", price: 2550 },
      { name: "Quail Meat (बट्टाई)/1 whole", price: 390 },
    ],
  },
  {
    category: "Party Platter",
    items: [
      { name: "Majheri Special Vegetarian Platter", price: 600 },
      { name: "Majheri Special Chicken Platter", price: 1000 },
      { name: "Majheri Special Mix Platter", price: 1200 },
      { name: "Majheri Special Wings Platter", price: 900 },
    ],
  },
  {
    category: "Sekuwa By Kilo",
    items: [
      { name: "Chicken Sekuwa Boneless/0.5KG", price: 825 },
      { name: "Chicken Wings/0.5KG", price: 750 },
      { name: "Pork Sekuwa/0.5KG", price: 875 },
      { name: "Buff Sekuwa/0.5KG", price: 750 },
      { name: "Mutton Sekuwa/0.5KG", price: 1575 },
    ],
  },
  {
    category: "Veg Appetizer",
    items: [
      { name: "French Fries", price: 220 },
      { name: "Mustang Alu", price: 250 },
      { name: "Papad Fry", price: 100 },
      { name: "Masala Papad", price: 200 },
      { name: "Crispy Spicy Potato", price: 245 },
      { name: "Chips Chilli", price: 340 },
      { name: "Paneer Pakoda", price: 350 },
      { name: "Paneer Chilli", price: 375 },
      { name: "Mushroom Chilli", price: 350 },
      { name: "Mushroom Choila", price: 300 },
      { name: "Waiwai Sadheko", price: 130 },
      { name: "Chatpat", price: 145 },
      { name: "Pani Puri", price: 145 },
      { name: "Onion Rings", price: 220 },
      { name: "Veg Pakoda/Aloo Chop", price: 210 },
      { name: "Crispy Corn", price: 350 },
      { name: "Peanut Sadheko", price: 225 },
      { name: "Bhatmas Sadheko", price: 215 },
      { name: "Cheese Ball", price: 400 },
      { name: "Crispy Veg", price: 250 },
    ],
  },
  {
    category: "Non-Veg Appetizer",
    items: [
      { name: "Timur Fire Chicken", price: 450 },
      { name: "Chicken Nuggets/Meatballs", price: 375 },
      { name: "Chicken Chilli", price: 400 },
      { name: "Chicken Sekuwa/Sadheko", price: 400 },
      { name: "Chicken Kurkure", price: 375 },
      { name: "Chicken Lolly Pop", price: 415 },
      { name: "Hot Chicken Wings", price: 450 },
      { name: "Chicken Choila", price: 345 },
      { name: "Buff Choila", price: 345 },
      { name: "Chicken Sausage (per Stick)", price: 95 },
      { name: "Buff Sausage (per Stick)", price: 95 },
      { name: "KFC Style Chicken Leg (Drumstick)", price: 500 },
      { name: "Fish Fingers", price: 400 },
      { name: "Fish Fry", price: 375 },
      { name: "Pork Tawa", price: 415 },
      { name: "Pork Sekuwa", price: 425 },
      { name: "Pork Chilli", price: 418 },
      { name: "Chicken Taas", price: 395 },
      { name: "Pork Taas", price: 425 },
      { name: "Mutton Taas", price: 540 },
      { name: "Buff Sekuwa", price: 380 },
      { name: "Buff Sukuti Fry", price: 375 },
      { name: "Buff Sukuti Sadheko", price: 390 },
    ],
  },
  {
    category: "Thakali Khana Set",
    items: [
        { name: "Veg Thali Set", price: 295 },
        { name: "Paneer Thali Set", price: 400 },
        { name: "Chicken Thali Set", price: 395 },
        { name: "Buff Thali Set", price: 375 },
        { name: "Pork Thali Set", price: 425 },
        { name: "Fish Thali Set", price: 450 },
        { name: "Mutton Thali Set", price: 600 },
        { name: "Local Chicken Thali Set", price: 575 },
    ],
  },
  {
    category: "Dhindo Thali Set",
    items: [
        { name: "Veg Dhindo Thali Set", price: 345 },
        { name: "Paneer Dhindo Thali Set", price: 450 },
        { name: "Chicken Dhindo Thali Set", price: 445 },
        { name: "Buff Dhindo Thali Set", price: 425 },
        { name: "Pork Dhindo Thali Set", price: 475 },
        { name: "Fish Dhindo Thali Set", price: 500 },
        { name: "Mutton Dhindo Thali Set", price: 650 },
        { name: "Local Chicken Dhindo Thali Set", price: 625 },
    ],
  },
  {
    category: "Marsi Rice Thali Set",
    items: [
        { name: "Veg Marsi Rice Thali Set", price: 425 },
        { name: "Paneer Marsi Rice Thali Set", price: 525 },
        { name: "Chicken Marsi Rice Thali Set", price: 520 },
        { name: "Buff Marsi Rice Thali Set", price: 500 },
        { name: "Pork Marsi Rice Thali Set", price: 550 },
        { name: "Fish Marsi Rice Thali Set", price: 575 },
        { name: "Mutton Marsi Rice Thali Set", price: 725 },
        { name: "Local Chicken Marsi Rice Thali Set", price: 700 },
    ],
  },
  {
    category: "Rice & Roti",
    items: [
      { name: "Plain Rice", price: 75 },
      { name: "Tawa Roti", price: 25 },
      { name: "Plain Paratha", price: 45 },
      { name: "Triangle Paratha", price: 65 },
      { name: "Aloo Paratha", price: 145 },
      { name: "Mix Veg Paratha", price: 195 },
      { name: "Keema Paratha", price: 265 },
    ],
  },
  {
    category: "Curries",
    items: [
      { name: "Mix Veg Curry", price: 170 },
      { name: "Matter Paneer", price: 350 },
      { name: "Paneer Masala", price: 350 },
      { name: "Chana Masala", price: 210 },
      { name: "Daal Tadka", price: 190 },
      { name: "Mushroom Matter Harya Pyaze", price: 250 },
      { name: "Egg Masala", price: 220 },
      { name: "Chicken Masala", price: 350 },
      { name: "Buff Masala", price: 340 },
      { name: "Pork Masala", price: 360 },
      { name: "Fish Masala", price: 370 },
      { name: "Chicken Curry Nepali Style", price: 350 },
      { name: "Mutton Curry Nepali Style", price: 650 },
      { name: "Fish Curry Nepali Style", price: 400 },
      { name: "Buff Curry Nepali Style", price: 400 },
      { name: "Pork Curry Nepali Style", price: 400 },
    ],
  },
  {
    category: "Coffee",
    items: [
      { name: "Espresso Single", price: 100 },
      { name: "Espresso Doppio", price: 160 },
      { name: "Americano Single", price: 95 },
      { name: "Americano Doppio", price: 130 },
      { name: "Milk Coffee", price: 120 },
      { name: "Cappuccino", price: 200 },
    ],
  },
  {
    category: "Iced Coffee & Tea",
    items: [
      { name: "Iced Americano", price: 185 },
      { name: "Iced Cappuccino", price: 240 },
      { name: "Iced Tea (Apple)", price: 185 },
      { name: "Iced Tea (Lemon)", price: 185 },
      { name: "Iced Tea (Peach)", price: 185 },
    ],
  },
  {
    category: "Milkshakes & Lassi",
    items: [
      { name: "Strawberry Milkshake", price: 250 },
      { name: "Vanilla Milkshake", price: 250 },
      { name: "Chocolate Milkshake", price: 250 },
      { name: "Oreo Milkshake", price: 270 },
      { name: "Plain Lassi", price: 150 },
      { name: "Sweet Lassi", price: 180 },
      { name: "Banana Lassi", price: 205 },
      { name: "Mix Lassi", price: 250 },
    ],
  },
  {
    category: "Hot Beverages",
    items: [
      { name: "Black Tea", price: 50 },
      { name: "Masala Black Tea", price: 80 },
      { name: "Normal Glass Milk Tea", price: 50 },
      { name: "Milk Tea Cup", price: 65 },
      { name: "Masala Milk Tea", price: 100 },
      { name: "Small Matka Tea", price: 70 },
      { name: "Big Matka Tea", price: 125 },
      { name: "Lemon Tea", price: 60 },
      { name: "Ginger Tea", price: 90 },
      { name: "Green Tea", price: 75 },
      { name: "Ginger & Lemon Tea", price: 110 },
      { name: "Hot Lemon", price: 95 },
      { name: "Hot Lemon with Ginger", price: 130 },
      { name: "Hot Lemon with Honey", price: 145 },
      { name: "Hot Lemon with Honey & Ginger", price: 165 },
      { name: "Hot Chocolate", price: 200 },
    ],
  },
  {
    category: "Bubble Tea",
    items: [
      { name: "Vanilla Bubble Tea", price: 250 },
      { name: "Chocolate Bubble Tea", price: 255 },
      { name: "Strawberry Bubble Tea", price: 255 },
      { name: "Blueberry Bubble Tea", price: 260 },
      { name: "Peach Bubble Tea", price: 250 },
    ],
  },
  {
    category: "Cold Beverages & Juices",
    items: [
      { name: "Coke/Fanta/Sprite", price: 85 },
      { name: "Masala Coke", price: 110 },
      { name: "Lemon Coke/Sprite", price: 100 },
      { name: "Plain Soda", price: 85 },
      { name: "Fresh Lemon Soda", price: 120 },
      { name: "Mahi (Mojito)", price: 85 },
      { name: "Masala Mahi", price: 130 },
      { name: "Water", price: 20 },
      { name: "Red Bull", price: 185 },
      { name: "Xtreme", price: 200 },
      { name: "Fresh Juice (Seasonal)", price: 250 },
      { name: "Fruit Juice (Orange/Apple/Cranberry/Pineapple)", price: 110 },
    ],
  },
  {
    category: "Mocktails",
    items: [
      { name: "Virgin Mojito", price: 230, description: "Sprite, Fresh Mint & Lemon Wedges" },
      { name: "Rocky Mouse", price: 220, description: "Vanilla Ice-Cream with Coke" },
      { name: "Fresh Lemonade", price: 120, description: "Lemon Juice, Sugar Syrup, Water" },
      { name: "Mint Lemonade", price: 150, description: "Lemon Juice, Sugar Syrup, Water, Mint" },
    ],
  },
  {
    category: "Cocktails",
    items: [
      { name: "Mojito", price: 500 },
      { name: "Hot Rum Punch", price: 500 },
      { name: "Jaeger Bomb", price: 850 },
    ],
  },
  {
    category: "Beers",
    items: [
      { name: "Carlsberg (660ml)", price: 675 },
      { name: "Tuborg (330ml)", price: 350 },
      { name: "Tuborg (660ml)", price: 625 },
      { name: "Budweiser (330ml)", price: 350 },
      { name: "Budweiser (660ml)", price: 625 },
      { name: "Barahsinghe (330ml)", price: 350 },
      { name: "Barahsinghe (660ml)", price: 625 },
      { name: "Gorkha Strong (330ml)", price: 295 },
      { name: "Gorkha Strong (660ml)", price: 550 },
      { name: "Arna Strong (330ml)", price: 295 },
      { name: "Arna Strong (660ml)", price: 550 },
    ],
  },
  {
    category: "Wines",
    items: [
      { name: "Robertson (Red/White)", price: 2800 },
      { name: "Santa Julia (Red/White)", price: 3600 },
      { name: "Big Master (Red/White)", price: 1290 },
      { name: "Jacob's Creek (Red/White)", price: 3330 },
      { name: "Porto Ruby (Red/White)", price: 4100 },
      { name: "Vesper (Red/White)", price: 3600 },
      { name: "Lolita (Red/White)", price: 3300 },
    ],
  },
  {
    category: "Whiskey",
    items: [
      { name: "JW Double Black (30ml)", price: 650 },
      { name: "JW Double Black (60ml)", price: 1220 },
      { name: "JW Black Label (30ml)", price: 560 },
      { name: "JW Black Label (60ml)", price: 1060 },
      { name: "Chivas Regal (30ml)", price: 590 },
      { name: "Chivas Regal (60ml)", price: 1130 },
      { name: "JW Red Label (30ml)", price: 470 },
      { name: "JW Red Label (60ml)", price: 870 },
      { name: "Vat 69 (30ml)", price: 430 },
      { name: "Vat 69 (60ml)", price: 790 },
      { name: "Ballantine (30ml)", price: 470 },
      { name: "Ballantine (60ml)", price: 880 },
      { name: "Glendiffich (12 years) (30ml)", price: 760 },
      { name: "Glendiffich (12 years) (60ml)", price: 1470 },
      { name: "Jameson (30ml)", price: 480 },
      { name: "Jameson (60ml)", price: 900 },
      { name: "Jack Daniel (30ml)", price: 560 },
      { name: "Jack Daniel (60ml)", price: 1020 },
    ],
  },
  {
    category: "Vodka",
    items: [
      { name: "Absolut Blue (30ml)", price: 460 },
      { name: "Absolut Blue (60ml)", price: 820 },
    ],
  },
  {
    category: "Domestic Spirits",
    items: [
      { name: "OD Black Chimney (30ml)", price: 270 },
      { name: "OD Black Chimney (60ml)", price: 530 },
      { name: "OD Reserve (30ml)", price: 210 },
      { name: "OD Reserve (60ml)", price: 390 },
      { name: "Signature Red (30ml)", price: 200 },
      { name: "Signature Red (60ml)", price: 370 },
      { name: "Signature Green (30ml)", price: 180 },
      { name: "Signature Green (60ml)", price: 360 },
      { name: "Gurkhas & Guns (30ml)", price: 230 },
      { name: "Gurkhas & Guns (60ml)", price: 410 },
      { name: "Khukuri Dark Rum (30ml)", price: 170 },
      { name: "Khukuri Dark Rum (60ml)", price: 300 },
      { name: "Khukuri White Rum (30ml)", price: 180 },
      { name: "Khukuri White Rum (60ml)", price: 320 },
      { name: "Snowman (30ml)", price: 180 },
      { name: "Snowman (60ml)", price: 350 },
      { name: "Ruslan Vodka (30ml)", price: 180 },
      { name: "Ruslan Vodka (60ml)", price: 340 },
      { name: "Mt. 8848 Vodka (30ml)", price: 180 },
      { name: "Mt. 8848 Vodka (60ml)", price: 340 },
    ],
  },
  {
    category: "Tobacco",
    items: [
      { name: "Hukka (Original)", price: 350 },
      { name: "Hukka (Coconut)", price: 450 },
      { name: "Hukka (Flavored)", price: 450 },
      { name: "Extra Coil (Regular)", price: 50 },
      { name: "Extra Coil (Coconut)", price: 80 },
      { name: "Shikhar Ice (Per Pc)", price: 25 },
      { name: "Surya Red/Light/Artic (Per Pc)", price: 30 },
    ],
  },
];

